repos:
  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.0
    hooks:
      - id: ruff