name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
            pip install build pyinstaller==4.10 numpy wheel 
            pip install -r requirements_exe_build.txt
            python setup.py bdist_wheel
            pip install -e . --no-deps
            pip install cmerg

      - name: Build a source tarball
        if: ${{ matrix.python-version == '3.9' && matrix.os == 'ubuntu-22.04' }}
        run: python -m build --sdist

      - name: Build a binary wheel
        run: python -m build --wheel

      - name: Build an executable
        shell: bash
        if: ${{ matrix.python-version == '3.10' }}
        run: |
            pip install build pyinstaller==4.10 numpy wheel
            pip install -r requirements_exe_build.txt
            python setup.py bdist_wheel
            pip install -e . --no-deps
            pip install cmerg
            if [ "$RUNNER_OS" == "Linux" ]; then
                 sudo apt update
                 sudo apt install libegl1
            fi
            pyinstaller asammdf.spec --distpath dist/${RUNNER_OS} --noconfirm --clean --onefile

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/**
          if-no-files-found: error

      # see: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      # - name: Publish distribution 📦 to PyPI
      #   if: startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
